import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../domain/models/fuel_entry.dart';
import '../../domain/models/maintenance.dart';
import '../../domain/models/vehicle.dart';
import '../../providers/auth_provider.dart';
import '../../providers/expense_provider.dart';
import '../../providers/vehicle_provider.dart';

const Color _kNavy = Color(0xFF0F1B2D);
const Color _kAccentBlue = Color(0xFF3B82F6);
const Color _kTextSecondary = Color(0xFF64748B);

// =============================================================================
// ADD VEHICLE DIALOG
// =============================================================================

Future<void> showAddVehicleDialog(BuildContext context, WidgetRef ref) async {
  await showDialog(
    context: context,
    builder: (context) => const _AddVehicleDialog(),
  );
}

class _AddVehicleDialog extends ConsumerStatefulWidget {
  const _AddVehicleDialog();

  @override
  ConsumerState<_AddVehicleDialog> createState() => _AddVehicleDialogState();
}

class _AddVehicleDialogState extends ConsumerState<_AddVehicleDialog> {
  final _formKey = GlobalKey<FormState>();
  final _marqueController = TextEditingController();
  final _modeleController = TextEditingController();
  final _anneeController = TextEditingController();
  final _immatriculationController = TextEditingController();
  bool _isLoading = false;

  @override
  void dispose() {
    _marqueController.dispose();
    _modeleController.dispose();
    _anneeController.dispose();
    _immatriculationController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    
    final userId = ref.read(currentUserIdProvider);
    if (userId == null) return;

    setState(() => _isLoading = true);
    
    try {
      final firestoreService = ref.read(firestoreServiceProvider);
      final v = Vehicle(
        id: '', // Generated by Firestore
        marque: _marqueController.text.trim(),
        modele: _modeleController.text.trim(),
        annee: int.parse(_anneeController.text.trim()),
        immatriculation: _immatriculationController.text.trim(),
      );
      
      await firestoreService.addVehicle(userId, v);
      ref.invalidate(vehiclesProvider);
      
      if (mounted) Navigator.of(context).pop();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Erreur: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Ajouter un véhicule', style: TextStyle(color: _kNavy, fontWeight: FontWeight.bold)),
      content: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextFormField(
                controller: _marqueController,
                decoration: const InputDecoration(labelText: 'Marque', border: OutlineInputBorder()),
                validator: (v) => v!.isEmpty ? 'Requis' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _modeleController,
                decoration: const InputDecoration(labelText: 'Modèle', border: OutlineInputBorder()),
                validator: (v) => v!.isEmpty ? 'Requis' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _anneeController,
                decoration: const InputDecoration(labelText: 'Année', border: OutlineInputBorder()),
                keyboardType: TextInputType.number,
                validator: (v) => v!.isEmpty ? 'Requis' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _immatriculationController,
                decoration: const InputDecoration(labelText: 'Immatriculation', border: OutlineInputBorder()),
                validator: (v) => v!.isEmpty ? 'Requis' : null,
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Annuler', style: TextStyle(color: _kTextSecondary)),
        ),
        ElevatedButton(
          style: ElevatedButton.styleFrom(backgroundColor: _kAccentBlue, foregroundColor: Colors.white),
          onPressed: _isLoading ? null : _submit,
          child: _isLoading ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2)) : const Text('Ajouter'),
        ),
      ],
    );
  }
}

// =============================================================================
// ADD MAINTENANCE DIALOG
// =============================================================================

Future<void> showAddMaintenanceDialog(BuildContext context, WidgetRef ref, String vehicleId) async {
  await showDialog(
    context: context,
    builder: (context) => _AddMaintenanceDialog(vehicleId: vehicleId),
  );
}

class _AddMaintenanceDialog extends ConsumerStatefulWidget {
  final String vehicleId;
  const _AddMaintenanceDialog({required this.vehicleId});

  @override
  ConsumerState<_AddMaintenanceDialog> createState() => _AddMaintenanceDialogState();
}

class _AddMaintenanceDialogState extends ConsumerState<_AddMaintenanceDialog> {
  final _formKey = GlobalKey<FormState>();
  final _descriptionController = TextEditingController();
  final _coutController = TextEditingController();
  final _categoryController = TextEditingController(text: 'cat_general');
  bool _isLoading = false;

  @override
  void dispose() {
    _descriptionController.dispose();
    _coutController.dispose();
    _categoryController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    
    final userId = ref.read(currentUserIdProvider);
    if (userId == null) return;

    setState(() => _isLoading = true);
    
    try {
      final firestoreService = ref.read(firestoreServiceProvider);
      final m = Maintenance(
        id: '', // Generated
        vehicleId: widget.vehicleId,
        date: DateTime.now(),
        categoryId: _categoryController.text.trim(),
        description: _descriptionController.text.trim(),
        cout: double.parse(_coutController.text.trim()),
      );
      
      await firestoreService.addMaintenance(userId, m);
      ref.invalidate(monthlyExpensesByVehicleProvider(widget.vehicleId));
      ref.invalidate(budgetBreakdownProvider);
      
      if (mounted) Navigator.of(context).pop();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Erreur: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Ajouter Maintenance', style: TextStyle(color: _kNavy, fontWeight: FontWeight.bold)),
      content: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextFormField(
                controller: _descriptionController,
                decoration: const InputDecoration(labelText: 'Description', border: OutlineInputBorder()),
                validator: (v) => v!.isEmpty ? 'Requis' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _coutController,
                decoration: const InputDecoration(labelText: 'Coût (MAD)', border: OutlineInputBorder()),
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                validator: (v) => v!.isEmpty ? 'Requis' : null,
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Annuler', style: TextStyle(color: _kTextSecondary)),
        ),
        ElevatedButton(
          style: ElevatedButton.styleFrom(backgroundColor: _kAccentBlue, foregroundColor: Colors.white),
          onPressed: _isLoading ? null : _submit,
          child: _isLoading ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2)) : const Text('Ajouter'),
        ),
      ],
    );
  }
}

// =============================================================================
// ADD FUEL DIALOG
// =============================================================================

Future<void> showAddFuelDialog(BuildContext context, WidgetRef ref, String vehicleId) async {
  await showDialog(
    context: context,
    builder: (context) => _AddFuelDialog(vehicleId: vehicleId),
  );
}

class _AddFuelDialog extends ConsumerStatefulWidget {
  final String vehicleId;
  const _AddFuelDialog({required this.vehicleId});

  @override
  ConsumerState<_AddFuelDialog> createState() => _AddFuelDialogState();
}

class _AddFuelDialogState extends ConsumerState<_AddFuelDialog> {
  final _formKey = GlobalKey<FormState>();
  final _litresController = TextEditingController();
  final _montantController = TextEditingController();
  final _kilometrageController = TextEditingController();
  bool _isLoading = false;

  @override
  void dispose() {
    _litresController.dispose();
    _montantController.dispose();
    _kilometrageController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    
    final userId = ref.read(currentUserIdProvider);
    if (userId == null) return;

    setState(() => _isLoading = true);
    
    try {
      final firestoreService = ref.read(firestoreServiceProvider);
      final f = FuelEntry(
        id: '', // Generated
        vehicleId: widget.vehicleId,
        date: DateTime.now(),
        litres: double.parse(_litresController.text.trim()),
        montant: double.parse(_montantController.text.trim()),
        kilometrage: double.parse(_kilometrageController.text.trim()),
      );
      
      await firestoreService.addFuelEntry(userId, f);
      ref.invalidate(fuelEntriesByVehicleProvider(widget.vehicleId));
      ref.invalidate(monthlyExpensesByVehicleProvider(widget.vehicleId));
      ref.invalidate(budgetBreakdownProvider);
      
      if (mounted) Navigator.of(context).pop();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Erreur: $e')));
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Ajouter Gasoil', style: TextStyle(color: _kNavy, fontWeight: FontWeight.bold)),
      content: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              TextFormField(
                controller: _litresController,
                decoration: const InputDecoration(labelText: 'Litres', border: OutlineInputBorder()),
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                validator: (v) => v!.isEmpty ? 'Requis' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _montantController,
                decoration: const InputDecoration(labelText: 'Montant (MAD)', border: OutlineInputBorder()),
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                validator: (v) => v!.isEmpty ? 'Requis' : null,
              ),
              const SizedBox(height: 12),
              TextFormField(
                controller: _kilometrageController,
                decoration: const InputDecoration(labelText: 'Kilométrage Actuel', border: OutlineInputBorder()),
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                validator: (v) => v!.isEmpty ? 'Requis' : null,
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Annuler', style: TextStyle(color: _kTextSecondary)),
        ),
        ElevatedButton(
          style: ElevatedButton.styleFrom(backgroundColor: _kAccentBlue, foregroundColor: Colors.white),
          onPressed: _isLoading ? null : _submit,
          child: _isLoading ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2)) : const Text('Ajouter'),
        ),
      ],
    );
  }
}
